In [1]:
# imports
from pathlib import Path
from time import time

import numpy as np
import pandas as pd

from utils import (
    read_single_problem_from_path_as_adjacency,
    read_single_problem_from_path_as_sparse,
    read_single_problem_from_path_as_sparse_from_adjacency,
    order_nodes_in_descending_order,
    check_validity_for_adjacency,
    transform_node_clique_to_zero_one,
    transform_zero_one_clique_to_nodes
)
from constants import BASE_INSTANCES_FILES, OTHER_INSTANCES_FILES, OTHER_INSTANCES_BEST_KNOWN
from heuristics import (
    HeuristicRunner,
    descending_degree_glutonous_heuristic,
    dynamic_descending_degree_glutonous_heuristic,
    descending_degree_random_heuristic,
    multiple_descending_degree_random_heuristic
)

# Constants
ROOT_DIR = Path.cwd().parent
# Instances pathes
INSTANCES_DIR = ROOT_DIR / "instances"
BASE_INSTANCES_DIR = INSTANCES_DIR / "project_instances"
OTHER_INSTANCES_DIR = INSTANCES_DIR / "other_instances"


In [2]:
_, _, graph, degrees = read_single_problem_from_path_as_adjacency(
    instance_path=BASE_INSTANCES_DIR / "random-10.col"
)
print(graph)
clique = descending_degree_glutonous_heuristic(graph=graph, degrees=degrees)
print(clique)
print("Is the clique valid ? ", check_validity_for_adjacency(graph, clique))


[[0 1 0 1 1 1 0 0 1 0]
 [1 0 1 0 1 0 1 1 1 1]
 [0 1 0 1 0 1 0 0 0 1]
 [1 0 1 0 0 0 0 0 1 0]
 [1 1 0 0 0 1 1 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 0 1 1 0 1 1 1]
 [0 1 0 0 1 0 1 0 0 1]
 [1 1 0 1 0 1 1 0 0 0]
 [0 1 1 0 1 0 1 1 0 0]]
[0 1 0 0 1 0 1 1 0 1]
Is the clique valid ?  True


In [3]:
# Check that clique representation utils work
number_of_nodes, _, graph, degrees = read_single_problem_from_path_as_adjacency(
    instance_path=BASE_INSTANCES_DIR / "random-10.col"
)
clique = descending_degree_glutonous_heuristic(graph=graph, degrees=degrees)
print(clique)
print(transform_zero_one_clique_to_nodes(clique))
print(transform_node_clique_to_zero_one(number_of_nodes, transform_zero_one_clique_to_nodes(clique)))

[0 1 0 0 1 0 1 1 0 1]
[1, 4, 6, 7, 9]
[0 1 0 0 1 0 1 1 0 1]


In [4]:
# Test on project instances
runner = HeuristicRunner(
    instances_dir=BASE_INSTANCES_DIR,
    instances=BASE_INSTANCES_FILES,
    methods=[
        (descending_degree_glutonous_heuristic, "desc_base"),
        (dynamic_descending_degree_glutonous_heuristic, "desc_dyn"),
        (descending_degree_random_heuristic, "desc_ran"),
        (multiple_descending_degree_random_heuristic, "mult_ran")
    ],
    known_bests={},
    display_time_details=False
)
runner.run_all_methods_on_all_instances()
runner.display_results()

{}
          instance     method clique best  total(s)
0   brock200_2.col  desc_base      7   //  0.131788
1   brock200_2.col   desc_dyn      7   //   0.16555
2   brock200_2.col   desc_ran      7   //  0.153766
3   brock200_2.col   mult_ran      8   //  0.277605
4              ///        ///    ///  ///       ///
5    dsjc125.1.col  desc_base      4   //  0.014187
6    dsjc125.1.col   desc_dyn      4   //   0.01527
7    dsjc125.1.col   desc_ran      4   //  0.018429
8    dsjc125.1.col   mult_ran      3   //  0.091107
9              ///        ///    ///  ///       ///
10   random-10.col  desc_base      5   //  0.001711
11   random-10.col   desc_dyn      5   //  0.008028
12   random-10.col   desc_ran      5   //  0.002008
13   random-10.col   mult_ran      5   //  0.006372
14             ///        ///    ///  ///       ///
15  random-100.col  desc_base      8   //  0.031495
16  random-100.col   desc_dyn      8   //  0.031066
17  random-100.col   desc_ran      8   //  0.029194
18  rando

In [5]:
# Test on other bigger instances.
runner = HeuristicRunner(
    instances_dir=OTHER_INSTANCES_DIR,
    instances=OTHER_INSTANCES_FILES,
    methods=[
        (descending_degree_glutonous_heuristic, "desc_base"),
        (dynamic_descending_degree_glutonous_heuristic, "desc_dyn"),
        (descending_degree_random_heuristic, "desc_ran"),
        (multiple_descending_degree_random_heuristic, "mult_ran")
    ],
    known_bests=OTHER_INSTANCES_BEST_KNOWN,
    display_time_details=False
)
runner.run_all_methods_on_all_instances()
runner.display_results()

{'brock800_4.txt': 26, 'C500.9.txt': 57, 'C2000.5.txt': 16, 'gen400_p0.9_75.txt': 75, 'p_hat700-1.txt': 11, 'p_hat1500-3.txt': 94}
              instance     method clique best  total(s)
0       brock800_4.txt  desc_base     14   26   1.66716
1       brock800_4.txt   desc_dyn     14   26  1.731732
2       brock800_4.txt   desc_ran     14   26  1.538241
3       brock800_4.txt   mult_ran     16   26  1.841554
4                  ///        ///    ///  ///       ///
5          C2000.5.txt  desc_base     10   16  5.731333
6          C2000.5.txt   desc_dyn     10   16  6.147654
7          C2000.5.txt   desc_ran     11   16  5.940005
8          C2000.5.txt   mult_ran     11   16  7.689719
9                  ///        ///    ///  ///       ///
10          C500.9.txt  desc_base     43   57  0.853878
11          C500.9.txt   desc_dyn     42   57  1.070398
12          C500.9.txt   desc_ran     44   57   0.98454
13          C500.9.txt   mult_ran     43   57  1.582353
14                 ///       

In [6]:
# Test different size of choices for the nodes for random heuristic
files = []
instance_reading_times = []
clique_creating_times = []
total_times = []
clique_sizes = []
methods = []

for file in ["brock200_2.col"]:
    for k in range(1, 11):
        # Method and file adding
        methods.append(f"multi_ran_{k}")
        files.append(file)

        # File loading
        start_time = time()
        _, _, graph, degrees = read_single_problem_from_path_as_adjacency(
            instance_path=BASE_INSTANCES_DIR / file
        )
        end_of_read_time = time()
        instance_reading_times.append(end_of_read_time - start_time)

        # Clique building
        clique = multiple_descending_degree_random_heuristic(graph=graph, degrees=degrees, size_of_choice=k, number_of_iterations=20)
        clique_sizes.append(np.sum(clique))
        end_of_clique_time = time()
        clique_creating_times.append(end_of_clique_time - end_of_read_time)

        assert check_validity_for_adjacency(graph, clique)
        total_times.append(time() - start_time)
    
    # At the end of each method, add visual separator
    for display_list in [files, instance_reading_times, clique_creating_times, total_times, clique_sizes, methods]:
        display_list.append("/////")


In [7]:
# Display for different size of choices for random heuristic

display_dataframe = pd.DataFrame(
    {
        "file": files,
        "method": methods,
        "clique size": clique_sizes,
        "instance time": instance_reading_times,
        "clique time": clique_creating_times,
        "total time": total_times,
    }
)
print(display_dataframe)

              file        method clique size instance time clique time  \
0   brock200_2.col   multi_ran_1           7      0.067228    0.220125   
1   brock200_2.col   multi_ran_2           7      0.069317    0.161296   
2   brock200_2.col   multi_ran_3           7      0.046943     0.20663   
3   brock200_2.col   multi_ran_4           8       0.05749    0.208605   
4   brock200_2.col   multi_ran_5           7        0.0737    0.204007   
5   brock200_2.col   multi_ran_6           7      0.054611    0.190381   
6   brock200_2.col   multi_ran_7           8      0.057433    0.177959   
7   brock200_2.col   multi_ran_8           8      0.056192    0.151159   
8   brock200_2.col   multi_ran_9           9       0.04989    0.190565   
9   brock200_2.col  multi_ran_10           7      0.063685    0.168607   
10           /////         /////       /////         /////       /////   

   total time  
0    0.288394  
1    0.231648  
2    0.253573  
3    0.266095  
4    0.277707  
5    0.245993  