In [8]:
# imports
from pathlib import Path
from time import time

import numpy as np
import pandas as pd

from utils import (read_single_problem_from_path_as_adjacency,
 read_single_problem_from_path_as_sparse, 
 read_single_problem_from_path_as_sparse_from_adjacency,
 order_nodes_in_descending_order,
 check_validity_for_adjacency)
from constants import BASE_INSTANCES_FILES
from heuristics import descending_degree_glutonous_heuristic

# Constants
ROOT_DIR = Path.cwd().parent
# Instances pathes
INSTANCES_DIR = ROOT_DIR / "instances"
BASE_INSTANCES_DIR = INSTANCES_DIR / "project_instances"
OTHER_INSTANCES_DR = INSTANCES_DIR / "other_instances"

In [9]:
_,_, graph, degrees = read_single_problem_from_path_as_adjacency(
        instance_path=BASE_INSTANCES_DIR / "random-10.col"
    )
print(graph)
clique =descending_degree_glutonous_heuristic(graph=graph, degrees=degrees)
print(clique)
print("Is the clique valid ? ", check_validity_for_adjacency(graph, clique))

[[0 1 0 1 1 1 0 0 1 0]
 [1 0 1 0 1 0 1 1 1 1]
 [0 1 0 1 0 1 0 0 0 1]
 [1 0 1 0 0 0 0 0 1 0]
 [1 1 0 0 0 1 1 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 0 1 1 0 1 1 1]
 [0 1 0 0 1 0 1 0 0 1]
 [1 1 0 1 0 1 1 0 0 0]
 [0 1 1 0 1 0 1 1 0 0]]
[4, 6, 5]
Is the clique valid ?  True


In [13]:
# Build clique size and times of execution for most basic heuristic
files = []
instance_reading_times = []
clique_creating_times = []
total_times = []
clique_sizes = []

for file in BASE_INSTANCES_FILES:
    files.append(file)

    start_time = time()
    _,_, graph, degrees = read_single_problem_from_path_as_adjacency(
            instance_path=BASE_INSTANCES_DIR / file
        )
    end_of_read_time = time()
    instance_reading_times.append(end_of_read_time - start_time)

    clique =descending_degree_glutonous_heuristic(graph=graph, degrees=degrees)
    clique_sizes.append(len(clique))
    end_of_clique_time = time()
    clique_creating_times.append(end_of_clique_time -end_of_read_time)

    assert(check_validity_for_adjacency(graph, clique))
    total_times.append(time() - start_time)


In [15]:
# Display for most basic heuristic

display_dataframe = pd.DataFrame({
    "file":files,
    "clique size": clique_sizes, 
    "instance time": instance_reading_times,
    "clique time":clique_creating_times,
    "total time" : total_times,
})
print(display_dataframe)

             file  clique size  instance time  clique time  total time
0  brock200_2.col            7       0.064044     0.003955    0.069035
1   dsjc125.1.col            3       0.004008     0.000986    0.004995
2   random-10.col            3       0.000969     0.000000    0.000969
3  random-100.col            7       0.013000     0.002032    0.015032
4   random-40.col            6       0.002012     0.000984    0.002996
5   random-70.col            6       0.006016     0.001993    0.008009
