In [1]:

# imports
from pathlib import Path
from time import time

import numpy as np

from utils import (read_single_problem_from_path_as_adjacency,
 read_single_problem_from_path_as_sparse, 
 read_single_problem_from_path_as_sparse_from_adjacency,
 order_nodes_in_descending_order)
from constants import BASE_INSTANCES_FILES

# Constants
ROOT_DIR = Path.cwd().parent
# Instances pathes
INSTANCES_DIR = ROOT_DIR / "instances"
BASE_INSTANCES_DIR = INSTANCES_DIR / "project_instances"
OTHER_INSTANCES_DIR = INSTANCES_DIR / "other_instances"

In [2]:
# Loading an instance
read_single_problem_from_path_as_adjacency(
    # instance_path=BASE_INSTANCES_DIR/ "brock200_2.col"
    instance_path=BASE_INSTANCES_DIR
    / "random-10.col"
)

(10,
 25,
 array([[0, 1, 0, 1, 1, 1, 0, 0, 1, 0],
        [1, 0, 1, 0, 1, 0, 1, 1, 1, 1],
        [0, 1, 0, 1, 0, 1, 0, 0, 0, 1],
        [1, 0, 1, 0, 0, 0, 0, 0, 1, 0],
        [1, 1, 0, 0, 0, 1, 1, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 0, 1, 1, 0, 1, 1, 1],
        [0, 1, 0, 0, 1, 0, 1, 0, 0, 1],
        [1, 1, 0, 1, 0, 1, 1, 0, 0, 0],
        [0, 1, 1, 0, 1, 0, 1, 1, 0, 0]], dtype=int8),
 array([5, 7, 4, 3, 6, 5, 6, 4, 5, 5], dtype=int8))

In [3]:

# Mean load time for adjacency
number_of_loads = 50

start_time = time()
for _ in range(number_of_loads):
    read_single_problem_from_path_as_adjacency(
        instance_path=BASE_INSTANCES_DIR / "brock200_2.col"
    )

print(f"Mean time from scratch:{(time() - start_time)/number_of_loads}")

Mean time from scratch:0.1329460334777832


In [4]:
# Creating sparse matrix either from adjacency or scratch and compare
(_, _, sparse, _) = read_single_problem_from_path_as_sparse_from_adjacency(
    # instance_path=BASE_INSTANCES_DIR/ "brock200_2.col"
    instance_path=BASE_INSTANCES_DIR
    / "brock200_2.col"
)

(_, _, sparse_scratch, _) = read_single_problem_from_path_as_sparse(
    # instance_path=BASE_INSTANCES_DIR/ "brock200_2.col"
    instance_path=BASE_INSTANCES_DIR
    / "brock200_2.col"
)
print(np.all(sparse.toarray() == sparse_scratch.toarray()))

# The result is now false because the construction of the base sparse matrix is done 
# as if the graph is oriented.

False


In [5]:
# Loading time compared from adjacency or scratch

number_of_loads = 50

start_time = time()
for _ in range(number_of_loads):
    read_single_problem_from_path_as_sparse(
        instance_path=BASE_INSTANCES_DIR / "brock200_2.col"
    )

print(f"Mean time from scratch:{(time() - start_time)/number_of_loads}")

start_time = time()
for _ in range(number_of_loads):
    read_single_problem_from_path_as_sparse_from_adjacency(
        instance_path=BASE_INSTANCES_DIR / "brock200_2.col"
    )

print(f"Mean time from adjacency:{(time() - start_time)/number_of_loads}")

Mean time from scratch:0.19208970546722412
Mean time from adjacency:0.16683557033538818


In [6]:
# Compared sizes of adjacency and sparse matrix
print("Instance // Size of sparse // Size of adjacency")
for file in BASE_INSTANCES_FILES:
    _, _, array, _ = read_single_problem_from_path_as_sparse_from_adjacency(BASE_INSTANCES_DIR / file)
    _, _, adjacency, _ = read_single_problem_from_path_as_adjacency(
        BASE_INSTANCES_DIR / file
    )
    from sys import getsizeof

    print(
        file,
        getsizeof(array.indices)
        + getsizeof(array.indptr)
        + getsizeof(array.data)
        + getsizeof(array),
        getsizeof(adjacency),
    )



Instance // Size of sparse // Size of adjacency
brock200_2.col 1188 40128
dsjc125.1.col 888 15753
random-10.col 428 228
random-100.col 788 10128
random-40.col 548 1728
random-70.col 668 5028


In [7]:
_,_,_, degrees = read_single_problem_from_path_as_sparse(
        instance_path=BASE_INSTANCES_DIR / "random-10.col"
    )

print(degrees)
print(order_nodes_in_descending_order(degrees))

[5 7 4 3 6 5 6 4 5 5]
[1 4 6 0 5 8 9 2 7 3]


In [8]:
_,_,graph, _ = read_single_problem_from_path_as_sparse(
        instance_path=BASE_INSTANCES_DIR / "random-10.col"
    )

_,_,graph_from_adj, _ = read_single_problem_from_path_as_sparse_from_adjacency(
        instance_path=BASE_INSTANCES_DIR / "random-10.col"
    )

print(graph.toarray())
print(graph_from_adj.toarray())
print(graph.indices)
print(graph_from_adj.indices)

[[0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0 0]
 [1 1 0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 0 0 0 0]
 [0 1 0 0 1 1 0 0 0 0]
 [0 1 0 0 1 0 1 0 0 0]
 [1 1 0 1 0 1 1 0 0 0]
 [0 1 1 0 1 0 1 1 0 0]]
[[0 1 0 1 1 1 0 0 1 0]
 [1 0 1 0 1 0 1 1 1 1]
 [0 1 0 1 0 1 0 0 0 1]
 [1 0 1 0 0 0 0 0 1 0]
 [1 1 0 0 0 1 1 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 0 1 1 0 1 1 1]
 [0 1 0 0 1 0 1 0 0 1]
 [1 1 0 1 0 1 1 0 0 0]
 [0 1 1 0 1 0 1 1 0 0]]
[0 1 0 2 0 1 0 2 4 1 4 5 1 4 6 0 1 3 5 6 1 2 4 6 7]
[1 3 4 5 8 0 2 4 6 7 8 9 1 3 5 9 0 2 8 0 1 5 6 7 9 0 2 4 6 8 1 4 5 7 8 9 1
 4 6 9 0 1 3 5 6 1 2 4 6 7]
