In [2]:
from time import time

import numpy as np

from utils.neighbourhood_utils import i_th_bit_flip_neighbourhood, i_th_nodes_removal_neighbour

In [3]:
# Building combinations.
import itertools

positions = np.arange(10)
print(list(itertools.combinations(positions, 2)))

[(0, 1), (0, 2), (0, 3), (0, 4), (0, 5), (0, 6), (0, 7), (0, 8), (0, 9), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6), (1, 7), (1, 8), (1, 9), (2, 3), (2, 4), (2, 5), (2, 6), (2, 7), (2, 8), (2, 9), (3, 4), (3, 5), (3, 6), (3, 7), (3, 8), (3, 9), (4, 5), (4, 6), (4, 7), (4, 8), (4, 9), (5, 6), (5, 7), (5, 8), (5, 9), (6, 7), (6, 8), (6, 9), (7, 8), (7, 9), (8, 9)]


In [4]:
# Building neighbourhood of a binary array
array = np.random.binomial(n=1, p=0.5, size=[10])
print(array)
# Display first ten neighbours
i_th_bit_flip_neighbourhood(array, i=3)[:10]

[1 1 1 0 1 0 0 1 1 1]


[array([0, 0, 0, 0, 1, 0, 0, 1, 1, 1]),
 array([0, 0, 1, 1, 1, 0, 0, 1, 1, 1]),
 array([0, 0, 1, 0, 0, 0, 0, 1, 1, 1]),
 array([0, 0, 1, 0, 1, 1, 0, 1, 1, 1]),
 array([0, 0, 1, 0, 1, 0, 1, 1, 1, 1]),
 array([0, 0, 1, 0, 1, 0, 0, 0, 1, 1]),
 array([0, 0, 1, 0, 1, 0, 0, 1, 0, 1]),
 array([0, 0, 1, 0, 1, 0, 0, 1, 1, 0]),
 array([0, 1, 0, 1, 1, 0, 0, 1, 1, 1]),
 array([0, 1, 0, 0, 0, 0, 0, 1, 1, 1])]

In [5]:
# Building neighbourhood of a bigger size
array = np.random.binomial(n=1, p=0.5, size=[200])
print(array)
# Display first ten neighbours
start = time()
for _ in range(5):
    i_th_bit_flip_neighbourhood(array, i=3)[:10]
print("Mean time", (time() - start)/20)

print(len(i_th_bit_flip_neighbourhood(array, i=3)))

[1 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 1 1 0 0 0 1 0 1 0 1 0 0
 1 1 1 1 0 1 1 0 1 1 0 0 1 0 1 1 0 1 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 1 0 1 1 0 1 0 1 0 1 0 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 0 0 0 0
 0 0 1 1 1 1 1 1 1 0 1 1 0 1 0 0 1 1 0 1 0 0 1 0 0 1 1 1 0 1 1 1 0 0 0 0 0
 0 1 0 1 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 1
 0 1 0 0 1 1 0 1 1 0 0 0 0 0 1]
Mean time 5.123775851726532
1313400


In [6]:
array = np.random.binomial(n=1, p=0.5, size=[10])
print(array)
print(i_th_nodes_removal_neighbour(array=array, i=1))
print(i_th_nodes_removal_neighbour(array=array, i=2))
print(i_th_nodes_removal_neighbour(array=array, i=3))

[0 0 1 1 1 0 0 1 1 1]
[7]
[4, 8]
[2, 7, 3]
